spring:
  elasticsearch:
    uris: http://localhost:9200
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    #设置确认方式 手动确认 fasle
    listener:
      simple:
        #默认auto自动确认
        acknowledge-mode: manual
        #每次push消息批量个数
        #prefetch: 10
        #是否每次拒绝reject 让消息重新进入队列 如果不重新入队 消息死信
        #reject-undelivered: false
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  #数据源连接
  datasource:
    url: jdbc:mysql://localhost:3306/charging?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#charging.emqx.**
charging:
  emqx:
    address: tcp://localhost:1883
    username: admin
    password: public
#配置调度中心属性
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
      accessToken: default_token
    executor:
      appname: order-executor
      ip:
      port: 19999
      logpath: /logs
      logretentiondays: 30
      address: